// WellWalk Pro v4.2 Beta - Production Ready
const APP_VERSION='4.2',WEATHER_API_KEY='DEMO_KEY';
const Q=[{text:"Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.",author:"Robert Collier"},{text:"Non conta quante volte cadi, ma quante volte ti rialzi.",author:"Vince Lombardi"},{text:"Il corpo raggiunge ciò che la mente crede.",author:"Napoleon Hill"},{text:"L'unico modo per fare un ottimo lavoro è amare quello che fai.",author:"Steve Jobs"},{text:"La motivazione ti fa iniziare. L'abitudine ti fa continuare.",author:"Jim Ryun"}];
const B=[{id:'first_walk',name:'Primo',icon:'🚶',requirement:1,type:'walks',desc:'Prima camminata'},{id:'week_warrior',name:'Guerriero',icon:'⚔️',requirement:7,type:'streak',desc:'7 giorni consecutivi'},{id:'month_master',name:'Maestro',icon:'👑',requirement:30,type:'streak',desc:'30 giorni'},{id:'distance_10',name:'10km',icon:'🎯',requirement:10,type:'distance',desc:'10km totali'},{id:'distance_50',name:'50km',icon:'🏆',requirement:50,type:'distance',desc:'50km totali'},{id:'routine_master',name:'Pro',icon:'✅',requirement:30,type:'routines',desc:'30 giorni completi'},{id:'early_bird',name:'Mattiniero',icon:'🌅',requirement:1,type:'special',desc:'Camminata < 8am'},{id:'night_owl',name:'Notturno',icon:'🌙',requirement:1,type:'special',desc:'Camminata > 22pm'}];
let currentDate=new Date(),routines=[],walkData={isActive:false,isPaused:false,startTime:null,elapsedTime:0,pausedTime:0,distance:0,positions:[],watchId:null},timerInterval=null,stepCounter={lastAcceleration:null,stepCount:0},recognition=null,transcriptText='';
function init(){checkVersion();const u=localStorage.getItem('wellwalk_user');u?(routines=JSON.parse(localStorage.getItem('wellwalk_routines')||'[]'),showScreen('screen-main'),loadMainScreen()):showScreen('screen-welcome');requestPermissions();loadWeatherAPI();registerSW()}
function checkVersion(){const s=localStorage.getItem('wellwalk_version');s&&s!==APP_VERSION&&console.log('Version:',s,'→',APP_VERSION);localStorage.setItem('wellwalk_version',APP_VERSION)}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').then(()=>console.log('✅ SW registered')).catch(e=>console.warn('SW error:',e))}
function requestPermissions(){'Notification'in window&&Notification.permission==='default'&&Notification.requestPermission()}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active')}
function saveProfile(){const n=document.getElementById('userName').value.trim();if(!n){alert('Inserisci nome');return}const u={name:n,age:document.getElementById('userAge').value||null,gender:document.getElementById('userGender').value||null,createdAt:new Date().toISOString()};localStorage.setItem('wellwalk_user',JSON.stringify(u));u.gender&&document.documentElement.setAttribute('data-gender',u.gender);showScreen('screen-routines');setTimeout(()=>addRoutine(),100)}
function addRoutine(){if(routines.length>=10){alert('Max 10');return}const l=document.getElementById('routineList'),i=document.createElement('div');i.style.cssText='display:flex;gap:12px;padding:14px;background:rgba(82,166,224,.06);border:2px solid var(--border);border-radius:14px;margin-bottom:10px';i.innerHTML=`<input type="text" placeholder="Es: Colazione..." data-index="${routines.length}" style="flex:1;border:none;background:transparent;padding:10px;font:inherit"><button class="icon-btn" onclick="removeRoutine(this)" style="width:40px;height:40px;background:var(--danger);color:#fff;border:none">✕</button>`;l.appendChild(i);routines.push('');updateRoutineCounter();routines.length>=10&&(document.getElementById('addRoutineBtn').disabled=true)}
function removeRoutine(btn){btn.parentElement.remove();routines.splice(parseInt(btn.previousElementSibling.dataset.index),1);document.querySelectorAll('#routineList input').forEach((i,idx)=>i.dataset.index=idx);updateRoutineCounter();document.getElementById('addRoutineBtn').disabled=false}
function updateRoutineCounter(){const c=document.getElementById('routineCount');c&&(c.textContent=routines.length)}
function saveRoutines(){routines=Array.from(document.querySelectorAll('#routineList input')).map(i=>i.value.trim()).filter(v=>v);if(!routines.length){alert('Almeno 1 routine');return}localStorage.setItem('wellwalk_routines',JSON.stringify(routines));showScreen('screen-main');loadMainScreen()}
function loadMainScreen(){const u=JSON.parse(localStorage.getItem('wellwalk_user'));document.getElementById('welcomeMessage').textContent=`Ciao, ${u.name}!`;u.gender&&document.documentElement.setAttribute('data-gender',u.gender);updateDate();updateQuote();loadRoutineChecklist();loadDayData();updateStreak();updateWeeklyAnalytics();updateBadges();loadQuotableAPI()}
function updateDate(){document.getElementById('currentDate').textContent=currentDate.toLocaleDateString('it-IT',{day:'numeric',month:'long'});document.getElementById('currentDay').textContent=currentDate.toLocaleDateString('it-IT',{weekday:'long'})}
function changeDay(d){currentDate.setDate(currentDate.getDate()+d);updateDate();loadDayData();updateWeeklyAnalytics()}
function updateQuote(){const d=Math.floor((currentDate-new Date(currentDate.getFullYear(),0,0))/86400000),q=Q[d%Q.length];document.getElementById('quoteText').textContent=`"${q.text}"`;document.getElementById('quoteAuthor').textContent=q.author}
async function loadQuotableAPI(){try{const r=await fetch('https://api.quotable.io/random?tags=inspirational|motivational');if(r.ok){const d=await r.json();document.getElementById('quoteText').textContent=`"${d.content}"`;document.getElementById('quoteAuthor').textContent=d.author}}catch(e){console.warn('Quote API:',e)}}
async function loadWeatherAPI(){if(!navigator.geolocation)return;try{const p=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej));const{latitude:lat,longitude:lon}=p.coords;const r=await fetch(`https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&appid=${WEATHER_API_KEY}&units=metric&lang=it`);if(r.ok){const d=await r.json();const icons={'Clear':'☀️','Clouds':'☁️','Rain':'🌧️','Snow':'❄️','Drizzle':'🌦️','Thunderstorm':'⛈️'};document.getElementById('weatherIcon').textContent=icons[d.weather[0].main]||'⛅';document.getElementById('weatherTemp').textContent=Math.round(d.main.temp)+'°';document.getElementById('weatherDesc').textContent=d.weather[0].description;document.getElementById('weatherWidget').classList.remove('hidden')}}catch(e){console.warn('Weather:',e)}}
function loadRoutineChecklist(){const l=document.getElementById('routineChecklist');l.innerHTML='';if(!routines.length){l.innerHTML='<p style="text-align:center;opacity:.5;padding:20px">Vai in Settings → Routine</p>';return}routines.forEach((r,i)=>{const it=document.createElement('div');it.className='routine-item';it.innerHTML=`<input type="checkbox" id="routine-${i}" onchange="saveRoutineCheck(${i})"><label for="routine-${i}">${r}</label>`;l.appendChild(it)});updateRoutineProgress()}
function saveRoutineCheck(i){const k=currentDate.toISOString().split('T')[0],cb=document.getElementById(`routine-${i}`);cb.parentElement.classList.toggle('completed',cb.checked);let d=getDayData(k);d.routines=d.routines||{};d.routines[i]=cb.checked;saveDayData(k,d);updateRoutineProgress();updateWeeklyAnalytics();checkBadgeProgress()}
function updateRoutineProgress(){const cbs=document.querySelectorAll('.routine-item input[type="checkbox"]'),t=cbs.length,c=Array.from(cbs).filter(cb=>cb.checked).length,p=t>0?Math.round((c/t)*100):0;document.getElementById('routineSummary').textContent=`${c}/${t}`;document.getElementById('progressBar').style.width=p+'%';document.getElementById('progressPercentage').textContent=p+'%';c===t&&t>0&&'Notification'in window&&Notification.permission==='granted'&&new Notification('WellWalk',{body:'🎉 Tutte le routine!'})}
function toggleWalk(){walkData.isActive?walkData.isPaused?resumeWalk():pauseWalk():startWalk()}
function startWalk(){walkData.isActive=true;walkData.isPaused=false;walkData.startTime=Date.now();walkData.elapsedTime=0;walkData.positions=[];walkData.distance=0;updateWalkButton();timerInterval=setInterval(updateTimer,1000);navigator.geolocation&&(walkData.watchId=navigator.geolocation.watchPosition(updatePosition,console.warn,{enableHighAccuracy:true}));window.DeviceMotionEvent&&(window.addEventListener('devicemotion',handleMotion),stepCounter.stepCount=0)}
function pauseWalk(){walkData.isPaused=true;walkData.pausedTime=Date.now();clearInterval(timerInterval);walkData.watchId&&(navigator.geolocation.clearWatch(walkData.watchId),walkData.watchId=null);window.removeEventListener('devicemotion',handleMotion);updateWalkButton()}
function resumeWalk(){walkData.isPaused=false;const p=Date.now()-walkData.pausedTime;walkData.startTime+=p;updateWalkButton();timerInterval=setInterval(updateTimer,1000);navigator.geolocation&&(walkData.watchId=navigator.geolocation.watchPosition(updatePosition,console.warn,{enableHighAccuracy:true}));window.DeviceMotionEvent&&window.addEventListener('devicemotion',handleMotion)}
function updateWalkButton(){const b=document.getElementById('walkBtn'),i=document.getElementById('walkBtnIcon'),t=document.getElementById('walkBtnText');walkData.isActive?walkData.isPaused?(b.className='btn btn-success',i.innerHTML='<path d="M5 3l14 9-14 9V3z"/>',t.textContent='Riprendi'):(b.className='btn btn-danger',i.innerHTML='<rect x="6" y="6" width="4" height="12"/><rect x="14" y="6" width="4" height="12"/>',t.textContent='Pausa'):(b.className='btn btn-success',i.innerHTML='<path d="M5 3l14 9-14 9V3z"/>',t.textContent='Inizia')}
function updateTimer(){walkData.elapsedTime=Date.now()-walkData.startTime;document.getElementById('timerDisplay').textContent=formatTime(walkData.elapsedTime);if(walkData.distance>0&&walkData.elapsedTime>0){const h=walkData.elapsedTime/3600000;document.getElementById('speedDisplay').textContent=(walkData.distance/h).toFixed(1)}document.getElementById('caloriesDisplay').textContent=Math.round(stepCounter.stepCount*0.05)}
function updatePosition(p){const n={lat:p.coords.latitude,lng:p.coords.longitude};if(walkData.positions.length>0){const l=walkData.positions[walkData.positions.length-1],d=calculateDistance(l.lat,l.lng,n.lat,n.lng);d>0.005&&(walkData.distance+=d,document.getElementById('distanceDisplay').textContent=walkData.distance.toFixed(2))}walkData.positions.push(n)}
function handleMotion(e){const a=e.accelerationIncludingGravity;if(!a||!a.x)return;const t=Math.sqrt(a.x**2+a.y**2+a.z**2);stepCounter.lastAcceleration&&Math.abs(t-stepCounter.lastAcceleration)>1.2&&stepCounter.stepCount++;stepCounter.lastAcceleration=t}
function calculateDistance(lat1,lon1,lat2,lon2){const R=6371,dLat=(lat2-lat1)*Math.PI/180,dLon=(lon2-lon1)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function formatTime(ms){const t=Math.floor(ms/1000),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function startRecording(){if(!('webkitSpeechRecognition'in window)){alert('Trascrizione non supportata. Usa textarea.');return}recognition=new webkitSpeechRecognition();recognition.continuous=true;recognition.interimResults=true;recognition.lang='it-IT';recognition.onstart=()=>{document.getElementById('startRecordBtn').disabled=true;document.getElementById('stopRecordBtn').disabled=false;document.getElementById('recordingIndicator').classList.remove('hidden');transcriptText=''};recognition.onresult=(e)=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++)e.results[i].isFinal?transcriptText+=e.results[i][0].transcript+' ':interim+=e.results[i][0].transcript;document.getElementById('brainstormNotes').value=transcriptText+interim};recognition.onerror=()=>stopRecording();recognition.start()}
function stopRecording(){recognition&&(recognition.stop(),recognition=null);document.getElementById('startRecordBtn').disabled=false;document.getElementById('stopRecordBtn').disabled=true;document.getElementById('recordingIndicator').classList.add('hidden');saveBrainstorm()}
function saveBrainstorm(){const n=document.getElementById('brainstormNotes').value,k=currentDate.toISOString().split('T')[0];let d=getDayData(k);d.brainstorm=n;saveDayData(k,d)}
function exportNotes(){const n=document.getElementById('brainstormNotes').value;if(!n){alert('Nessuna nota');return}try{const b=new Blob([n],{type:'text/plain'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=`notes_${currentDate.toISOString().split('T')[0]}.txt`;document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(()=>URL.revokeObjectURL(url),100);alert('✅ Esportato!')}catch{alert('Errore export')}}
function toggleRoutines(){toggle('routinesContent','routinesIcon')}
function toggleBrainstorm(){toggle('brainstormContent','brainstormIcon')}
function toggleMusic(){toggle('musicContent','musicIcon')}
function toggleBadges(){toggle('badgesContent','badgesIcon')}
function toggleAnalytics(){toggle('analyticsContent','analyticsIcon')}
function toggle(c,i){document.getElementById(c).classList.toggle('expanded');document.getElementById(i).classList.toggle('rotated')}
function updateStreak(){document.getElementById('streakDays').textContent=calculateStreak()}
function calculateStreak(){let s=0;const t=new Date();t.setHours(0,0,0,0);for(let i=0;i<365;i++){const d=new Date(t);d.setDate(t.getDate()-i);const k=d.toISOString().split('T')[0],data=getDayData(k);if((data.routines&&Object.values(data.routines).some(v=>v))||data.walk||data.brainstorm)s++;else break}return s}
function updateWeeklyAnalytics(){const g=document.getElementById('weekGrid');g.innerHTML='';const w=['Dom','Lun','Mar','Mer','Gio','Ven','Sab'],t=new Date(currentDate),s=new Date(t);s.setDate(t.getDate()-t.getDay());let a=0,km=0,tR=0,cR=0;for(let i=0;i<7;i++){const d=new Date(s);d.setDate(s.getDate()+i);const k=d.toISOString().split('T')[0],data=getDayData(k),hasAct=(data.routines&&Object.values(data.routines).some(v=>v))||data.walk;hasAct&&a++;data.walk&&(km+=data.walk.distance||0);if(data.routines){const vals=Object.values(data.routines);vals.forEach((v,idx)=>{if(idx<routines.length){tR++;v&&cR++}})}const c=document.createElement('div');c.className='day-cell'+(hasAct?' active':'');c.innerHTML=`<div class="day-name">${w[i]}</div><div>${hasAct?'✓':'−'}</div>`;c.onclick=()=>showDayDetail(d);g.appendChild(c)}document.getElementById('activeDays').textContent=`${a}/7`;document.getElementById('totalKm').textContent=`${km.toFixed(1)} km`;const rp=tR>0?Math.round((cR/tR)*100):0;document.getElementById('completedRoutines').textContent=`${rp}%`}
function showDayDetail(date){const k=date.toISOString().split('T')[0],data=getDayData(k),title=date.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'});document.getElementById('dayModalTitle').textContent=title;let html='';if(data.routines){const rl=routines.map((r,i)=>`<div style="display:flex;gap:10px;margin-bottom:8px"><span>${data.routines[i]?'✅':'⬜'}</span><span>${r}</span></div>`).join('');html+=`<h3 style="margin-bottom:12px">Routine</h3>${rl}`}data.walk&&(html+=`<h3 style="margin:20px 0 12px">Camminata</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div style="text-align:center;padding:14px;background:rgba(82,166,224,.08);border-radius:12px"><div style="font-size:1.6rem;font-weight:800;color:var(--primary)">${(data.walk.distance||0).toFixed(2)}</div><div style="font-size:.75rem">km</div></div><div style="text-align:center;padding:14px;background:rgba(82,166,224,.08);border-radius:12px"><div style="font-size:1.6rem;font-weight:800;color:var(--primary)">${formatTime(data.walk.duration||0)}</div><div style="font-size:.75rem">tempo</div></div></div>`);data.brainstorm&&(html+=`<h3 style="margin:20px 0 12px">Note</h3><div style="padding:14px;background:rgba(82,166,224,.08);border-radius:12px">${data.brainstorm}</div>`);html||(html='<p style="text-align:center;opacity:.5;padding:30px">Nessuna attività</p>');document.getElementById('dayModalContent').innerHTML=html;document.getElementById('dayModal').classList.add('active')}
function closeDayModal(){document.getElementById('dayModal').classList.remove('active')}
function updateBadges(){const g=document.getElementById('badgesGrid');g.innerHTML='';const u=JSON.parse(localStorage.getItem('wellwalk_badges')||'[]');B.forEach(b=>{const isU=u.includes(b.id),badge=document.createElement('div');badge.className='badge'+(isU?' unlocked':'');badge.innerHTML=`<div class="badge-icon">${b.icon}</div><div class="badge-name">${b.name}</div>`;badge.onclick=()=>showBadgeModal(b,isU);g.appendChild(badge)})}
function showBadgeModal(b,u){document.getElementById('badgeModalIcon').textContent=b.icon;document.getElementById('badgeModalTitle').textContent=b.name;document.getElementById('badgeModalDesc').textContent=u?`✅ ${b.desc}`:`🔒 ${b.desc}`;document.getElementById('badgeModal').classList.add('active')}
function closeBadgeModal(){document.getElementById('badgeModal').classList.remove('active')}
function checkBadgeProgress(){const u=JSON.parse(localStorage.getItem('wellwalk_badges')||'[]'),nb=[];B.forEach(b=>{if(u.includes(b.id))return;let p=0;b.type==='walks'?p=countTotalWalks():b.type==='streak'?p=calculateStreak():b.type==='distance'?p=calculateTotalDistance():b.type==='routines'&&(p=countCompletedRoutineDays());p>=b.requirement&&(u.push(b.id),nb.push(b))});nb.length&&(localStorage.setItem('wellwalk_badges',JSON.stringify(u)),updateBadges(),nb.forEach(b=>'Notification'in window&&Notification.permission==='granted'&&new Notification('Traguardo!',{body:`${b.icon} ${b.name}`})))}
function countTotalWalks(){return Object.keys(localStorage).filter(k=>k.startsWith('wellwalk_day_')&&JSON.parse(localStorage[k]).walk).length}
function calculateTotalDistance(){let t=0;Object.keys(localStorage).forEach(k=>{if(k.startsWith('wellwalk_day_')){const d=JSON.parse(localStorage[k]);d.walk?.distance&&(t+=d.walk.distance)}});return t}
function countCompletedRoutineDays(){let c=0;Object.keys(localStorage).forEach(k=>{if(k.startsWith('wellwalk_day_')){const d=JSON.parse(localStorage[k]);if(d.routines){const v=Object.values(d.routines);v.length&&v.every(x=>x)&&c++}}});return c}
function getDayData(k){return JSON.parse(localStorage.getItem(`wellwalk_day_${k}`)||'{}')}
function saveDayData(k,d){localStorage.setItem(`wellwalk_day_${k}`,JSON.stringify(d))}
function loadDayData(){const k=currentDate.toISOString().split('T')[0],d=getDayData(k);document.querySelectorAll('.routine-item input[type="checkbox"]').forEach((cb,i)=>{cb.checked=d.routines?.[i]||false;cb.parentElement.classList.toggle('completed',cb.checked)});d.walk?(document.getElementById('timerDisplay').textContent=formatTime(d.walk.duration||0),document.getElementById('distanceDisplay').textContent=(d.walk.distance||0).toFixed(2),document.getElementById('caloriesDisplay').textContent=Math.round((d.walk.steps||0)*0.05)):(document.getElementById('timerDisplay').textContent='00:00:00',document.getElementById('distanceDisplay').textContent='0.0',document.getElementById('caloriesDisplay').textContent='0');document.getElementById('speedDisplay').textContent='0.0';document.getElementById('brainstormNotes').value=d.brainstorm||'';updateRoutineProgress();updateWalkButton()}
function showSettings(){document.getElementById('settingsModal').classList.add('active');const t=document.documentElement.getAttribute('data-theme');document.getElementById('themeToggle').classList.toggle('active',t==='dark')}
function closeSettings(){document.getElementById('settingsModal').classList.remove('active')}
function toggleTheme(){const h=document.documentElement,c=h.getAttribute('data-theme'),n=c==='dark'?'light':'dark';h.setAttribute('data-theme',n);localStorage.setItem('wellwalk_theme',n);document.getElementById('themeToggle').classList.toggle('active',n==='dark')}
function editProfile(){closeSettings();showScreen('screen-welcome');const u=JSON.parse(localStorage.getItem('wellwalk_user'));document.getElementById('userName').value=u.name;document.getElementById('userAge').value=u.age||'';document.getElementById('userGender').value=u.gender||''}
function editRoutines(){closeSettings();showScreen('screen-routines');const l=document.getElementById('routineList');l.innerHTML='';routines=JSON.parse(localStorage.getItem('wellwalk_routines')||'[]');routines.forEach(()=>addRoutine());document.querySelectorAll('#routineList input').forEach((i,idx)=>i.value=routines[idx]||'')}
function exportData(){try{const all={user:JSON.parse(localStorage.getItem('wellwalk_user')),routines,badges:JSON.parse(localStorage.getItem('wellwalk_badges')||'[]'),version:APP_VERSION,exportDate:new Date().toISOString(),days:{}};Object.keys(localStorage).forEach(k=>k.startsWith('wellwalk_day_')&&(all.days[k.replace('wellwalk_day_','')]=JSON.parse(localStorage[k])));const b=new Blob([JSON.stringify(all,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=`wellwalk_${new Date().toISOString().split('T')[0]}.json`;document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(()=>URL.revokeObjectURL(url),100);closeSettings();alert('✅ Dati esportati!')}catch{alert('Errore export')}}
function resetApp(){confirm('⚠️ Cancellare TUTTI i dati?')&&confirm('Ultima conferma?')&&(localStorage.clear(),alert('Reset completato'),location.reload())}
window.addEventListener('click',e=>{e.target===document.getElementById('settingsModal')&&closeSettings();e.target===document.getElementById('badgeModal')&&closeBadgeModal();e.target===document.getElementById('dayModal')&&closeDayModal()});
init();
const st=localStorage.getItem('wellwalk_theme'),sg=JSON.parse(localStorage.getItem('wellwalk_user')||'{}').gender;
st&&document.documentElement.setAttribute('data-theme',st);
sg&&document.documentElement.setAttribute('data-gender',sg);
console.log('✅ WellWalk Pro v'+APP_VERSION);
